version: "3" # Specify the Docker Compose version

services:
  # Node.js Backend Service
  db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: adminUser
      MONGO_INITDB_ROOT_PASSWORD: securePassword # Use an official Node.js image

    ports:
      - 27017:27017 # Map port 3000 of the container to port 3000 of the host
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
